import React, { useState, useEffect } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  Image,
  TouchableOpacity,
  Alert,
  Share,
  Modal,
  Dimensions,
} from 'react-native';
import { TextInput, Button } from 'react-native-paper';
import { useRouter, useLocalSearchParams } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useAppStore } from '../../store/useAppStore';
import { useTheme } from '../../hooks/useTheme';
import { WarrantyBadge } from '../../components/WarrantyBadge';
import { LoadingSpinner } from '../../components/LoadingSpinner';
import { getReceipt, updateReceipt, deleteReceipt } from '../../services/receiptsService';
import { deleteReceiptImage } from '../../services/storageService';
import { cancelWarrantyNotifications } from '../../services/notificationService';
import { formatDate, formatCurrency, getWarrantyStatus, daysUntilExpiry } from '../../utils/dateHelpers';
import { FONTS, SPACING, BORDER_RADIUS, SHADOW, CATEGORY_ICONS, CATEGORY_LABELS } from '../../utils/constants';
import { Receipt } from '../../types';

const { width: SW, height: SH } = Dimensions.get('window');

export default function ReceiptDetailScreen() {
  const router = useRouter();
  const { id } = useLocalSearchParams<{ id: string }>();
  const { currentUser, receipts } = useAppStore();
  const { colors } = useTheme();
  const [receipt, setReceipt] = useState<Receipt | null>(null);
  const [loading, setLoading] = useState(true);
  const [editing, setEditing] = useState(false);
  const [saving, setSaving] = useState(false);
  const [imageModal, setImageModal] = useState(false);

  const [editName, setEditName] = useState('');
  const [editStore, setEditStore] = useState('');
  const [editNotes, setEditNotes] = useState('');

  useEffect(() => {
    const local = receipts.find((r) => r.id === id);
    if (local) { setReceipt(local); setEditName(local.productName); setEditStore(local.storeName); setEditNotes(local.notes); setLoading(false); return; }
    if (currentUser?.uid && id) {
      getReceipt(currentUser.uid, id).then((r) => {
        if (r) { setReceipt(r); setEditName(r.productName); setEditStore(r.storeName); setEditNotes(r.notes); }
      }).catch(console.error).finally(() => setLoading(false));
    }
  }, [id, receipts, currentUser]);

  const handleSave = async () => {
    if (!currentUser?.uid || !receipt) return;
    try {
      setSaving(true);
      await updateReceipt(currentUser.uid, receipt.id, { productName: editName, storeName: editStore, notes: editNotes });
      setReceipt({ ...receipt, productName: editName, storeName: editStore, notes: editNotes });
      setEditing(false);
    } catch { Alert.alert('Error', 'Failed to save.'); }
    finally { setSaving(false); }
  };

  const handleDelete = () => {
    Alert.alert('Delete Receipt', 'This cannot be undone.', [
      { text: 'Cancel', style: 'cancel' },
      { text: 'Delete', style: 'destructive', onPress: async () => {
        if (!currentUser?.uid || !receipt) return;
        try {
          const nids = [receipt.notificationId30Days, receipt.notificationId7Days].filter(Boolean) as string[];
          if (nids.length) await cancelWarrantyNotifications(nids);
          await deleteReceiptImage(currentUser.uid, receipt.id);
          await deleteReceipt(currentUser.uid, receipt.id);
          router.back();
        } catch { Alert.alert('Error', 'Failed to delete.'); }
      }},
    ]);
  };

  const handleClaim = async () => {
    if (!receipt) return;
    const msg = `WARRANTY CLAIM SUMMARY\n━━━━━━━━━━━━━━━━━━━━━━\nProduct: ${receipt.productName}\nPurchased from: ${receipt.storeName}\nPurchase Date: ${formatDate(receipt.purchaseDate)}\nAmount Paid: ${formatCurrency(receipt.amount)}\nWarranty Period: ${receipt.warrantyMonths} months\nWarranty Expires: ${formatDate(receipt.warrantyExpiryDate)}\nNotes: ${receipt.notes || 'N/A'}\n━━━━━━━━━━━━━━━━━━━━━━\nGenerated by ReceiptVault`;
    try { await Share.share({ message: msg, title: `Warranty — ${receipt.productName}` }); } catch {}
  };

  if (loading) return <LoadingSpinner fullScreen message="Loading..." />;
  if (!receipt) return (
    <SafeAreaView style={[styles.container, { backgroundColor: colors.background }]} edges={['top']}>
      <View style={styles.notFound}><Text style={styles.notFoundEmoji}>🔍</Text>
        <Text style={[styles.notFoundText, { color: colors.textSecondary }]}>Receipt not found</Text>
        <Button mode="text" onPress={() => router.back()}>Go Back</Button>
      </View>
    </SafeAreaView>
  );

  const warrantyStatus = getWarrantyStatus(receipt.hasWarranty, receipt.warrantyExpiryDate);
  const statusColor = warrantyStatus === 'good' ? colors.success : warrantyStatus === 'warning' ? colors.warning : warrantyStatus === 'critical' || warrantyStatus === 'expired' ? colors.danger : colors.textTertiary;

  return (
    <SafeAreaView style={[styles.container, { backgroundColor: colors.background }]} edges={['top']}>
      <ScrollView contentContainerStyle={styles.scroll} showsVerticalScrollIndicator={false}>
        <View style={styles.header}>
          <TouchableOpacity onPress={() => router.back()}>
            <Text style={[styles.backBtn, { color: colors.primary }]}>← Back</Text>
          </TouchableOpacity>
          <TouchableOpacity onPress={() => setEditing(!editing)}>
            <Text style={[styles.editBtn, { color: colors.primary }]}>{editing ? 'Cancel' : '✏️ Edit'}</Text>
          </TouchableOpacity>
        </View>

        {receipt.imageUri ? (
          <TouchableOpacity onPress={() => setImageModal(true)} activeOpacity={0.9}>
            <Image source={{ uri: receipt.imageUri }} style={styles.heroImage} resizeMode="cover" />
          </TouchableOpacity>
        ) : (
          <View style={[styles.noImage, { backgroundColor: colors.borderLight }]}>
            <Text style={styles.noImageIcon}>{CATEGORY_ICONS[receipt.category] || '📦'}</Text>
          </View>
        )}

        {editing ? (
          <TextInput value={editName} onChangeText={setEditName} mode="outlined" label="Product Name"
            style={[styles.editInput, { backgroundColor: colors.inputBg }]}
            outlineColor={colors.border} activeOutlineColor={colors.primary} textColor={colors.textPrimary} />
        ) : (
          <Text style={[styles.productTitle, { color: colors.textPrimary }]}>{receipt.productName}</Text>
        )}

        <View style={[styles.infoCard, { backgroundColor: colors.card }, SHADOW.sm]}>
          <InfoRow emoji="🏪" label="Store" value={editing ? undefined : receipt.storeName} editing={editing} editValue={editing ? editStore : undefined} onEdit={editing ? setEditStore : undefined} />
          <InfoRow emoji="📅" label="Purchased" value={formatDate(receipt.purchaseDate)} />
          <InfoRow emoji="💰" label="Amount" value={formatCurrency(receipt.amount)} />
          <InfoRow emoji={CATEGORY_ICONS[receipt.category] || '📦'} label="Category" value={CATEGORY_LABELS[receipt.category] || receipt.category} />
          {receipt.hasWarranty && (
            <View style={[styles.infoRow, { borderBottomColor: colors.borderLight }]}>
              <Text style={styles.infoEmoji}>🛡️</Text>
              <View style={styles.infoContent}>
                <Text style={[styles.infoLabel, { color: colors.textTertiary }]}>WARRANTY</Text>
                <Text style={[styles.infoValue, { color: statusColor }]}>
                  {receipt.warrantyMonths}mo — expires {formatDate(receipt.warrantyExpiryDate)}
                </Text>
                <WarrantyBadge hasWarranty={receipt.hasWarranty} expiryDate={receipt.warrantyExpiryDate} />
              </View>
            </View>
          )}
          {(receipt.notes || editing) && (
            <InfoRow emoji="📝" label="Notes" value={editing ? undefined : receipt.notes || 'None'} editing={editing} editValue={editing ? editNotes : undefined} onEdit={editing ? setEditNotes : undefined} multiline />
          )}
        </View>

        {editing ? (
          <Button mode="contained" onPress={handleSave} loading={saving} disabled={saving}
            style={styles.actionBtn} buttonColor={colors.primary} labelStyle={styles.actionLabel}>Save Changes</Button>
        ) : (
          <>
            {receipt.hasWarranty && (
              <Button mode="contained" onPress={handleClaim} style={styles.actionBtn} buttonColor={colors.primary}
                icon="share-variant" labelStyle={styles.actionLabel}>Generate Claim Summary</Button>
            )}
            <Button mode="outlined" onPress={handleDelete} style={[styles.actionBtn, { borderColor: colors.danger }]}
              textColor={colors.danger} icon="delete-outline" labelStyle={styles.actionLabel}>Delete Receipt</Button>
          </>
        )}
      </ScrollView>

      <Modal visible={imageModal} transparent animationType="fade">
        <TouchableOpacity style={styles.modalOverlay} activeOpacity={1} onPress={() => setImageModal(false)}>
          <Image source={{ uri: receipt.imageUri }} style={styles.modalImg} resizeMode="contain" />
          <TouchableOpacity style={styles.modalClose} onPress={() => setImageModal(false)}>
            <Text style={styles.modalCloseText}>✕</Text>
          </TouchableOpacity>
        </TouchableOpacity>
      </Modal>
    </SafeAreaView>
  );
}

function InfoRow({ emoji, label, value, editing, editValue, onEdit, multiline }: {
  emoji: string; label: string; value?: string; editing?: boolean; editValue?: string; onEdit?: (v: string) => void; multiline?: boolean;
}) {
  const { colors } = useTheme();
  return (
    <View style={[irStyles.row, { borderBottomColor: colors.borderLight }]}>
      <Text style={irStyles.emoji}>{emoji}</Text>
      <View style={irStyles.content}>
        <Text style={[irStyles.label, { color: colors.textTertiary }]}>{label.toUpperCase()}</Text>
        {editing && onEdit ? (
          <TextInput value={editValue} onChangeText={onEdit} mode="outlined" dense multiline={multiline}
            style={[irStyles.editInput, { backgroundColor: colors.inputBg }]}
            outlineColor={colors.border} activeOutlineColor={colors.primary} textColor={colors.textPrimary} />
        ) : (
          <Text style={[irStyles.value, { color: colors.textPrimary }]}>{value}</Text>
        )}
      </View>
    </View>
  );
}

const irStyles = StyleSheet.create({
  row: { flexDirection: 'row', paddingVertical: SPACING.md, borderBottomWidth: 1 },
  emoji: { fontSize: 18, marginRight: SPACING.md, marginTop: 2 },
  content: { flex: 1 },
  label: { fontSize: FONTS.sizes.xs, fontWeight: '600', marginBottom: 2, letterSpacing: 0.5 },
  value: { fontSize: FONTS.sizes.base, fontWeight: '500' },
  editInput: { marginTop: SPACING.xs },
});

const styles = StyleSheet.create({
  container: { flex: 1 },
  scroll: { paddingBottom: SPACING['3xl'] },
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: SPACING.xl, paddingVertical: SPACING.md },
  backBtn: { fontSize: FONTS.sizes.base, fontWeight: '600' },
  editBtn: { fontSize: FONTS.sizes.base, fontWeight: '600' },
  heroImage: { width: '100%', height: 220 },
  noImage: { width: '100%', height: 120, justifyContent: 'center', alignItems: 'center' },
  noImageIcon: { fontSize: 48 },
  productTitle: { fontSize: FONTS.sizes['2xl'], fontWeight: '800', paddingHorizontal: SPACING.xl, paddingTop: SPACING.base, paddingBottom: SPACING.sm },
  editInput: { marginHorizontal: SPACING.xl, marginTop: SPACING.base },
  infoCard: { marginHorizontal: SPACING.xl, borderRadius: BORDER_RADIUS.xl, padding: SPACING.base, marginTop: SPACING.md },
  infoRow: { flexDirection: 'row', paddingVertical: SPACING.md, borderBottomWidth: 1 },
  infoEmoji: { fontSize: 18, marginRight: SPACING.md, marginTop: 2 },
  infoContent: { flex: 1 },
  infoLabel: { fontSize: FONTS.sizes.xs, fontWeight: '600', marginBottom: 2, letterSpacing: 0.5 },
  infoValue: { fontSize: FONTS.sizes.base, fontWeight: '500', marginBottom: SPACING.xs },
  actionBtn: { marginHorizontal: SPACING.xl, marginTop: SPACING.md, borderRadius: BORDER_RADIUS.md, paddingVertical: 2 },
  actionLabel: { fontSize: FONTS.sizes.base, fontWeight: '700', paddingVertical: 2 },
  notFound: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  notFoundEmoji: { fontSize: 56, marginBottom: SPACING.base },
  notFoundText: { fontSize: FONTS.sizes.lg, marginBottom: SPACING.md },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.9)', justifyContent: 'center', alignItems: 'center' },
  modalImg: { width: SW, height: SH * 0.8 },
  modalClose: { position: 'absolute', top: 50, right: 20, width: 40, height: 40, borderRadius: 20, backgroundColor: 'rgba(255,255,255,0.2)', justifyContent: 'center', alignItems: 'center' },
  modalCloseText: { color: '#fff', fontSize: 20, fontWeight: '700' },
});
